# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ v1Release ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        cd /var/www/html/DecryptNFTMarketplace/
        rm -rf *
        cp -a /root/actions-runner/staging-decryptnft-io/DecryptNFTMarketplace/DecryptNFTMarketplace/. /var/www/html/DecryptNFTMarketplace/
        cd /var/www/html/DecryptNFTMarketplace/backend
        pwd
        npm i
        pm2 kill
        pm2 start 'node index.js'
